### ISSUE TITLE
Map Designer

### ISSUE THREAD

**Issue by PriyanshuDangi** [delta/codecharacter-web-2022#2]
Rough design sketch: https://jamboard.google.com/d/1DUagRDEAVROzsPEKXSLJfn2ANVQTCU1aVqCuL1-rwCo/edit?usp=sharing
page 2

Assets
https://www.kenney.nl/assets/isometric-blocks
Use any 2 different blocks for the towers 

Tasks:
- [x] UI for controls and buttons
- [x] Phaser Map (Basic 64x64 in isometric) 
- [ ] Integrating Controls with the map

**Comment by jaiakash** [comment]
I designed the map as 64 by 64 hexagon grid with 60 degree tillted.
Right now grid colour changes when user clicks on it. 
Hexagonal grid code : http://csharphelper.com/blog/2015/10/draw-a-hexagonal-grid-in-c/
![Screenshot from 2022-01-04 00-56-54](https://user-images.githubusercontent.com/33419526/147971716-8bb93961-4fef-4ba7-887d-6a8fec63ff4a.png)

**Comment by Ram-20062003** [comment]
Added buttons and coin text to the map-designer UI
1. Made three-tower buttons 
2. Added Coins
3. Made save button with a drop-down having a commit button
4. Buttons are made interactive
